---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: {% if DEPLOYMENT == 'prod' %}{{DOCKER_REGISTRY}}/{% endif %}{{SERVER_IMAGE}}{% if IMAGES_VERSION %}:{{IMAGES_VERSION}}{% endif %}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: REANA_WORKFLOW_CONTROLLER_URL
          value: "/reana"
