---
apiVersion: v1
kind: Pod
metadata:
  name: storage-admin
spec:
  containers:
  - name: storage-admin
    image: {% if DEPLOYMENT == 'prod' %}{{DOCKER_REGISTRY}}/{% endif %}{{STORAGE_ADMIN_IMAGE}}{% if IMAGES_VERSION %}:{{IMAGES_VERSION}}{% endif %}
    imagePullPolicy: {{IMAGE_PULL_POLICY}}
    volumeMounts:
    - mountPath: "/reana"
      name: reana-shared-volume
    command:
    - "/bin/sleep"
    - '100000'
  volumes:
  - name: reana-shared-volume
    {% if DEPLOYMENT == 'prod' %}
      {% set shared_volume=ROOT_SHARED_VOLUME.PROD %}
    {% else %}
      {% set shared_volume=ROOT_SHARED_VOLUME.LOCAL %}
    {% endif %}
    {% if shared_volume.TYPE == 'cephfs' %}
    cephfs:
      monitors:
      {% for monitor in shared_volume.MONITORS  %}
       - {{monitor}}
      {% endfor %}
      path: {{shared_volume.PATH}}
      user: {{shared_volume.USER}}
      secretRef:
        name: {{shared_volume.SECRET_NAME}}
      readOnly: {{shared_volume.READONLY}}
    {% elif shared_volume.TYPE == 'hostpath' %}
    hostPath:
      path: {{shared_volume.PATH}}
    {% endif %}
