---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeromq-msg-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zeromq-msg-proxy
    spec:
      containers:
      - name: zeromq-msg-proxy
        image: {% if DEPLOYMENT == 'prod' %}{{DOCKER_REGISTRY}}/{% endif %}{{ZERO_MQ_IMAGE}}{% if IMAGES_VERSION %}:{{IMAGES_VERSION}}{% endif %}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        ports:
        - containerPort: 8666
        - containerPort: 8667
        command:
        - sh
        - "-c"
        - cd tracker; python proxy.py
